### ISSUE TITLE
tidy tuesday 2 exercise cut off

### ISSUE THREAD

**Issue by andreashandel** [rfranci3/RaquelFrancisco-MADA-portfolio#4]
For some reason, the website only shows part of your tidy tuesday 2 exercise, the output is cut off right when you formulate the hypothesis. can you check/fix?

**Comment by rfranci3** [comment]
That’s strange… I’ll look! Best wishes,Raquel Francisco, MS DVMGraduate Assistant (she/her/hers)Warnell School of Forestry and Natural ResourcesUniversity of ***@***.***; +1 (786) 326-1073 From: Andreas HandelSent: Wednesday, April 19, 2023 11:33 AMTo: rfranci3/RaquelFrancisco-MADA-portfolioCc: SubscribedSubject: [rfranci3/RaquelFrancisco-MADA-portfolio] tidy tuesday 2 exercise cut off (Issue #4) For some reason, the website only shows part of your tidy tuesday 2 exercise, the output is cut off right when you formulate the hypothesis. can you check/fix?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by rfranci3** [comment]
@andreashandel I have troubleshot the script. There was some bumps with rendering for whatever reason. All the script is now present on the website. Thank you for calling this to my attention!
